export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_TASKS_PENDING = "FETCH_TASKS_PENDING";
export const FETCH_TASKS_RESOLVED = "FETCH_TASKS_RESOLVED";
export const FETCH_TASKS_REJECTED = "FETCH_TASKS_REJECTED";

export const DUMMY_ACTION = "DUMMY_ACTION";
